const MAX_MULTIPLIER = 15;
const MIN_MULTIPLIER = 1;
const PRIMES = [3, 5, 7, 11];
const SCALE_NUMBER_DECIMAL_PLACES = 1;

export { MAX_MULTIPLIER, PRIMES, MIN_MULTIPLIER, SCALE_NUMBER_DECIMAL_PLACES };
