const SCALE_CLASS = 'slider__scale';
const LINE_CLASS = `${SCALE_CLASS}-line`;
const MARK_CLASS = `${SCALE_CLASS}-mark`;
const MARK_NUMBER_CLASS = `${SCALE_CLASS}-number`;
const MAX_MULTIPLIER = 15;
const MIN_MULTIPLIER = 1;
const PRIMES = [3, 5, 7, 11];
const SCALE_NUMBER_DECIMAL_PLACES = 1;

export {
  MAX_MULTIPLIER,
  PRIMES,
  MIN_MULTIPLIER,
  SCALE_NUMBER_DECIMAL_PLACES,
  SCALE_CLASS,
  MARK_CLASS,
  MARK_NUMBER_CLASS,
  LINE_CLASS,
};
