const FIRST_SLIDER_SELECTOR = '.js-slider-1';
const SECOND_SLIDER_SELECTOR = '.js-slider-2';
const THIRD_SLIDER_SELECTOR = '.js-slider-3';
const FOURTH_SLIDER_SELECTOR = '.js-slider-4';

export {
  FIRST_SLIDER_SELECTOR,
  SECOND_SLIDER_SELECTOR,
  THIRD_SLIDER_SELECTOR,
  FOURTH_SLIDER_SELECTOR,
};
